using System.IO.Abstractions;
using System.Text.Encodings.Web;
using System.Text.Json;
using DrillPress.Presets;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace DrillPress.LinqCatalogue;

public sealed class CatalogueGenerator(IFileSystem fileSystem)
{
    public void Write(string[] arguments)
    {
        if (arguments.Length != 4)
            throw new ArgumentException(
                "Supply output path and the net8.0, net9.0 and net10.0 reference-pack directories."
            );
        var entries = new Dictionary<string, LinqCatalogueEntry>();
        for (var index = 0; index < 3; index++)
        {
            var references = fileSystem
                .Directory.GetFiles(arguments[index + 1], "*.dll")
                .Select(path =>
                    MetadataReference.CreateFromImage(fileSystem.File.ReadAllBytes(path))
                );
            var compilation = CSharpCompilation.Create("Catalogue", references: references);
            foreach (var owner in new[] { "System.Linq.Enumerable", "System.Linq.Queryable" })
            foreach (
                var method in compilation
                    .GetTypeByMetadataName(owner)!
                    .GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(method =>
                        method.DeclaredAccessibility == Accessibility.Public && method.IsStatic
                    )
            )
            {
                var signature = LinqSignature.Of(method);
                var category = Category(method.Name);
                var parameters = method
                    .Parameters.Where(parameter => IsSequence(parameter.Type))
                    .Select(parameter => parameter.Ordinal)
                    .ToArray();
                if (entries.TryGetValue(signature, out var existing))
                {
                    if (
                        existing.Category != category
                        || !existing.SequenceParameters.SequenceEqual(parameters)
                    )
                        throw new InvalidDataException(
                            $"Framework classifications disagree for {signature}."
                        );
                    entries[signature] = existing with
                    {
                        Frameworks = existing.Frameworks | (1 << index),
                    };
                }
                else
                    entries.Add(signature, new(signature, category, 1 << index, parameters));
            }
        }
        var rows = entries
            .Values.OrderBy(entry => entry.Signature)
            .Select(entry =>
                $"        new({JsonSerializer.Serialize(entry.Signature, new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping })}, LinqOperationCategory.{entry.Category}, {entry.Frameworks}, [{string.Join(", ", entry.SequenceParameters)}]),"
            );
        fileSystem.File.WriteAllText(
            arguments[0],
            "// Generated by tools/DrillPress.LinqCatalogue from the supported framework reference packs.\n"
                + "namespace DrillPress.Presets;\n\ninternal static class LinqCatalogueData\n{\n"
                + "    public static IReadOnlyList<LinqCatalogueEntry> Entries { get; } = Array.AsReadOnly<LinqCatalogueEntry>([\n"
                + string.Join("\n", rows)
                + "\n    ]);\n}\n"
        );
        Console.WriteLine($"Recorded {entries.Count} exact overloads.");
    }

    private static bool IsSequence(ITypeSymbol type) =>
        type is IArrayTypeSymbol
        || type is INamedTypeSymbol named
            && named.OriginalDefinition.ToDisplayString()
                is "System.Collections.IEnumerable"
                    or "System.Collections.Generic.IEnumerable<T>"
                    or "System.Linq.IQueryable"
                    or "System.Linq.IQueryable<T>"
                    or "System.Linq.IOrderedQueryable<T>"
                    or "System.Linq.IOrderedEnumerable<TElement>";

    private static LinqOperationCategory Category(string name) =>
        name switch
        {
            "Aggregate"
            or "All"
            or "Any"
            or "Average"
            or "Contains"
            or "Count"
            or "ElementAt"
            or "ElementAtOrDefault"
            or "First"
            or "FirstOrDefault"
            or "Last"
            or "LastOrDefault"
            or "LongCount"
            or "Max"
            or "MaxBy"
            or "Min"
            or "MinBy"
            or "SequenceEqual"
            or "Single"
            or "SingleOrDefault"
            or "Sum"
            or "TryGetNonEnumeratedCount" => LinqOperationCategory.Scalar,
            "ToArray" or "ToDictionary" or "ToHashSet" or "ToList" or "ToLookup" =>
                LinqOperationCategory.Materializer,
            "AsEnumerable" or "AsQueryable" => LinqOperationCategory.Adapter,
            "Empty" or "Range" or "Repeat" or "InfiniteSequence" or "Sequence" =>
                LinqOperationCategory.SequenceFactory,
            "AggregateBy"
            or "Append"
            or "Cast"
            or "Chunk"
            or "Concat"
            or "CountBy"
            or "DefaultIfEmpty"
            or "Distinct"
            or "DistinctBy"
            or "Except"
            or "ExceptBy"
            or "GroupBy"
            or "GroupJoin"
            or "Index"
            or "Intersect"
            or "IntersectBy"
            or "Join"
            or "LeftJoin"
            or "OfType"
            or "Order"
            or "OrderDescending"
            or "OrderBy"
            or "OrderByDescending"
            or "Prepend"
            or "Reverse"
            or "RightJoin"
            or "Select"
            or "SelectMany"
            or "Shuffle"
            or "Skip"
            or "SkipLast"
            or "SkipWhile"
            or "Take"
            or "TakeLast"
            or "TakeWhile"
            or "ThenBy"
            or "ThenByDescending"
            or "Where"
            or "Union"
            or "UnionBy"
            or "Zip" => LinqOperationCategory.DeferredConstruction,
            _ => throw new InvalidDataException(
                $"Review the category of the new standard operation {name} before regenerating."
            ),
        };
}
