<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DrillPress.Core/DrillPress.Core.csproj" />
    <ProjectReference Include="../../src/DrillPress.SampleRules/DrillPress.SampleRules.csproj" />
  </ItemGroup>
</Project>
