<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DrillPress.RuleAuthoring/DrillPress.RuleAuthoring.csproj" />
    <ProjectReference Include="../../src/DrillPress.Engine/DrillPress.Engine.csproj" />
  </ItemGroup>
</Project>
