<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DrillPress.Engine" />
    <InternalsVisibleTo Include="DrillPress.BuildHost" />
    <InternalsVisibleTo Include="DrillPress.UnitTests" />
    <InternalsVisibleTo Include="DrillPress.IntegrationTests" />
    <InternalsVisibleTo Include="DrillPress.Cli" />
    <InternalsVisibleTo Include="DrillPress.BundleVerification" />
    <InternalsVisibleTo Include="DrillPress.Benchmarks" />
  </ItemGroup>
</Project>
