<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DrillPress.Engine" />
    <InternalsVisibleTo Include="DrillPress.UnitTests" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <ProjectReference Include="../DrillPress.Manifest/DrillPress.Manifest.csproj" />
  </ItemGroup>
</Project>
