<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <ProjectReference Include="../DrillPress.BundleVerification/DrillPress.BundleVerification.csproj" />
    <ProjectReference Include="../DrillPress.Conformance/DrillPress.Conformance.csproj" />
  </ItemGroup>
</Project>
